### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: Rapid Response Team Case Studies
# Write a short description for the site. This is used for "meta description."
description: "An exploration of the Rapid Response team's work and projects."

# Enable for live hosting on GitHub Pages
# This should match the name of your GitHub repository, along with a leading forward slash (/).
baseurl: /rapid-response-team-case-studies

### RECOMMENDED SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]

# Remove generation of additional style.css
theme: null