### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: Rapid Response Team
# Write a short description for the site. This is used for "meta description."
description: "Bixal's Rapid Response team is a pilot project to explore new business opportunities by engaging in structured design challenges, self-directed initiatives, and open-source projects. This site provides an exploration of the team's of processes on some of their most recent projects."

# Enable for live hosting on GitHub Pages
# This should match the name of your GitHub repository, along with a leading forward slash (/).
baseurl: /rapid-response-team

### RECOMMENDED SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]

# Remove generation of additional style.css
theme: null
